### ISSUE TITLE
Hubot won't start

### ISSUE THREAD

**Issue by riordan** [pelias/hubot#3]
```
2016-01-12T21:57:57.601476+00:00 app[web.1]: [Tue Jan 12 2016 21:57:57 GMT+0000 (UTC)] ERROR Unable to load /app/scripts/search: SyntaxError: Unexpected token ILLEGAL
2016-01-12T21:57:57.601488+00:00 app[web.1]:   at SlackBot.g (events.js:180:16)
2016-01-12T21:57:57.601495+00:00 app[web.1]:   at Receiver.expectHandler (/app/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:384:31)
2016-01-12T21:57:57.601480+00:00 app[web.1]:   at Module._compile (module.js:439:25)
2016-01-12T21:57:57.601489+00:00 app[web.1]:   at SlackBot.emit (events.js:92:17)
2016-01-12T21:57:57.601496+00:00 app[web.1]:   at Receiver.add (/app/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:93:24)
2016-01-12T21:57:57.601481+00:00 app[web.1]:   at Object.Module._extensions..js (module.js:474:10)
2016-01-12T21:57:57.601490+00:00 app[web.1]:   at SlackBot.open (/app/node_modules/hubot-slack/src/slack.coffee:100:5, <js>:143:19)
2016-01-12T21:57:57.601497+00:00 app[web.1]:   at CleartextStream.firstHandler (/app/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:678:22)
2016-01-12T21:57:57.601482+00:00 app[web.1]:   at Module.load (/app/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
2016-01-12T21:57:57.601490+00:00 app[web.1]:   at Client.<anonymous> (/app/node_modules/hubot-slack/src/slack.coffee:1:1, <js>:3:61)
2016-01-12T21:57:57.601498+00:00 app[web.1]:   at CleartextStream.emit (events.js:95:17)
2016-01-12T21:57:57.601483+00:00 app[web.1]:   at Function.Module._load (module.js:312:12)
2016-01-12T21:57:57.601491+00:00 app[web.1]:   at Client.emit (events.js:92:17)
2016-01-12T21:57:57.601498+00:00 app[web.1]:   at CleartextStream.<anonymous> (_stream_readable.js:765:14)
2016-01-12T21:57:58.661517+00:00 heroku[web.1]: Process exited with status 1
2016-01-12T21:57:58.684859+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by riordan** [comment]
This is probably my own damn fault on #1
